/**
 * @author Felipe Rodrigues Michetti
 * @see http://portfolio-frmichetti.rhcloud.com
 * @see http://www.codecode.com.br
 * @see mailto:frmichetti@gmail.com
 */
package br.com.frmichetti.carhollics.android.model;


import java.io.Serializable;

/**
 * SystemRole generated by hbm2java Generated Aug 29, 2016 9:15:47 PM by
 * Hibernate Tools 5.1.0.Alpha2 Only for Compatibility
 *
 * @since 1.0
 * @version
 */

public class SystemRole implements Serializable {

    private static final long serialVersionUID = -3259219990958750371L;

    private String name;

    public SystemRole() {
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
